name: jspdf
version: 1.0.0
description: jsPDF wrapper for Dart
homepage: https://github.com/insinfo/jspdf_dart.dart

environment:
  sdk: ^3.2.1

dependencies:
  js: ^0.7.0

dev_dependencies:  
  build_runner: any #2.4.8
  build_web_compilers: any #4.0.9
  lints: ^2.1.0
  test: ^1.24.0